# Generated by Django 5.1.6 on 2025-03-01 17:07

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('content_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('document', 'Document'), ('other', 'Autre')], default='other', max_length=50)),
                ('is_malicious', models.BooleanField(default=False, help_text="Score de confiance de l'analyse (0 à 1)")),
                ('analysis_report', models.FileField(upload_to=detection.models.upload_to_reports)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
