# Generated by Django 5.1.6 on 2025-03-02 19:59

import detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_analysisresult_risk_score_analysisresult_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='analysis_report',
            field=models.FileField(blank=True, null=True, upload_to=detection.models.upload_to_reports),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='is_malicious',
            field=models.BooleanField(default=False, help_text='Indique si le contenu est malveillant'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
