# Generated by Django 5.1.6 on 2025-03-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_analysisresult_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
